In [98]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import preprocessing, metrics
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
sns.set(style="white", color_codes=True)

In [99]:
import warnings
warnings.filterwarnings("ignore")

# 1st question

In [100]:
dtst = pd.read_csv('C:/Users/deeks/Downloads/datasets(2)/datasets/CC.csv')

In [101]:
dtst

CUST_ID      BALANCE  BALANCE_FREQUENCY  PURCHASES  ONEOFF_PURCHASES  \
0     C10001    40.900749           0.818182      95.40              0.00   
1     C10002  3202.467416           0.909091       0.00              0.00   
2     C10003  2495.148862           1.000000     773.17            773.17   
3     C10004  1666.670542           0.636364    1499.00           1499.00   
4     C10005   817.714335           1.000000      16.00             16.00   
...      ...          ...                ...        ...               ...   
8945  C19186    28.493517           1.000000     291.12              0.00   
8946  C19187    19.183215           1.000000     300.00              0.00   
8947  C19188    23.398673           0.833333     144.40              0.00   
8948  C19189    13.457564           0.833333       0.00              0.00   
8949  C19190   372.708075           0.666667    1093.25           1093.25   

      INSTALLMENTS_PURCHASES  CASH_ADVANCE  PURCHASES_FREQUENCY  \
0                      95.40      0.000000             0.166667   
1                       0.00   6442.945483             0.000000   
2                       0.00      0.000000             1.000000   
3                       0.00    205.788017             0.083333   
4                       0.00      0.000000             0.083333   
...                      ...           ...                  ...   
8945                  291.12      0.000000             1.000000   
8946                  300.00      0.000000             1.000000   
8947                  144.40      0.000000             0.833333   
8948                    0.00     36.558778             0.000000   
8949                    0.00    127.040008             0.666667   

      ONEOFF_PURCHASES_FREQUENCY  PURCHASES_INSTALLMENTS_FREQUENCY  \
0                       0.000000                          0.083333   
1                       0.000000                          0.000000   
2                       1.000000                          0.000000   
3                       0.083333                          0.000000   
4                       0.083333                          0.000000   
...                          ...                               ...   
8945                    0.000000                          0.833333   
8946                    0.000000                          0.833333   
8947                    0.000000                          0.666667   
8948                    0.000000                          0.000000   
8949                    0.666667                          0.000000   

      CASH_ADVANCE_FREQUENCY  CASH_ADVANCE_TRX  PURCHASES_TRX  CREDIT_LIMIT  \
0                   0.000000                 0              2        1000.0   
1                   0.250000                 4              0        7000.0   
2                   0.000000                 0             12        7500.0   
3                   0.083333                 1              1        7500.0   
4                   0.000000                 0              1        1200.0   
...                      ...               ...            ...           ...   
8945                0.000000                 0              6        1000.0   
8946                0.000000                 0              6        1000.0   
8947                0.000000                 0              5        1000.0   
8948                0.166667                 2              0         500.0   
8949                0.333333                 2             23        1200.0   

         PAYMENTS  MINIMUM_PAYMENTS  PRC_FULL_PAYMENT  TENURE  
0      201.802084        139.509787          0.000000      12  
1     4103.032597       1072.340217          0.222222      12  
2      622.066742        627.284787          0.000000      12  
3        0.000000               NaN          0.000000      12  
4      678.334763        244.791237          0.000000      12  
...           ...               ...               ...     ...  
8945   325.594462         48.886365  

In [102]:
dtst.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8950 entries, 0 to 8949
Data columns (total 18 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   CUST_ID                           8950 non-null   object 
 1   BALANCE                           8950 non-null   float64
 2   BALANCE_FREQUENCY                 8950 non-null   float64
 3   PURCHASES                         8950 non-null   float64
 4   ONEOFF_PURCHASES                  8950 non-null   float64
 5   INSTALLMENTS_PURCHASES            8950 non-null   float64
 6   CASH_ADVANCE                      8950 non-null   float64
 7   PURCHASES_FREQUENCY               8950 non-null   float64
 8   ONEOFF_PURCHASES_FREQUENCY        8950 non-null   float64
 9   PURCHASES_INSTALLMENTS_FREQUENCY  8950 non-null   float64
 10  CASH_ADVANCE_FREQUENCY            8950 non-null   float64
 11  CASH_ADVANCE_TRX                  8950 non-null   int64  
 12  PURCHA

In [103]:
dtst.head()

CUST_ID      BALANCE  BALANCE_FREQUENCY  PURCHASES  ONEOFF_PURCHASES  \
0  C10001    40.900749           0.818182      95.40              0.00   
1  C10002  3202.467416           0.909091       0.00              0.00   
2  C10003  2495.148862           1.000000     773.17            773.17   
3  C10004  1666.670542           0.636364    1499.00           1499.00   
4  C10005   817.714335           1.000000      16.00             16.00   

   INSTALLMENTS_PURCHASES  CASH_ADVANCE  PURCHASES_FREQUENCY  \
0                    95.4      0.000000             0.166667   
1                     0.0   6442.945483             0.000000   
2                     0.0      0.000000             1.000000   
3                     0.0    205.788017             0.083333   
4                     0.0      0.000000             0.083333   

   ONEOFF_PURCHASES_FREQUENCY  PURCHASES_INSTALLMENTS_FREQUENCY  \
0                    0.000000                          0.083333   
1                    0.000000                          0.000000   
2                    1.000000                          0.000000   
3                    0.083333                          0.000000   
4                    0.083333                          0.000000   

   CASH_ADVANCE_FREQUENCY  CASH_ADVANCE_TRX  PURCHASES_TRX  CREDIT_LIMIT  \
0                0.000000                 0              2        1000.0   
1                0.250000                 4              0        7000.0   
2                0.000000                 0             12        7500.0   
3                0.083333                 1              1        7500.0   
4                0.000000                 0              1        1200.0   

      PAYMENTS  MINIMUM_PAYMENTS  PRC_FULL_PAYMENT  TENURE  
0   201.802084        139.509787          0.000000      12  
1  4103.032597       1072.340217          0.222222      12  
2   622.066742        627.284787          0.000000      12  
3     0.000000               NaN          0.000000      12  
4   678.334763        244.791237          0.000000      12

In [104]:
dtst.isnull().any()

CUST_ID                             False
BALANCE                             False
BALANCE_FREQUENCY                   False
PURCHASES                           False
ONEOFF_PURCHASES                    False
INSTALLMENTS_PURCHASES              False
CASH_ADVANCE                        False
PURCHASES_FREQUENCY                 False
ONEOFF_PURCHASES_FREQUENCY          False
PURCHASES_INSTALLMENTS_FREQUENCY    False
CASH_ADVANCE_FREQUENCY              False
CASH_ADVANCE_TRX                    False
PURCHASES_TRX                       False
CREDIT_LIMIT                         True
PAYMENTS                            False
MINIMUM_PAYMENTS                     True
PRC_FULL_PAYMENT                    False
TENURE                              False
dtype: bool

In [105]:
dtst.fillna(dtst.mean(), inplace=True)
dtst.isnull().any()

CUST_ID                             False
BALANCE                             False
BALANCE_FREQUENCY                   False
PURCHASES                           False
ONEOFF_PURCHASES                    False
INSTALLMENTS_PURCHASES              False
CASH_ADVANCE                        False
PURCHASES_FREQUENCY                 False
ONEOFF_PURCHASES_FREQUENCY          False
PURCHASES_INSTALLMENTS_FREQUENCY    False
CASH_ADVANCE_FREQUENCY              False
CASH_ADVANCE_TRX                    False
PURCHASES_TRX                       False
CREDIT_LIMIT                        False
PAYMENTS                            False
MINIMUM_PAYMENTS                    False
PRC_FULL_PAYMENT                    False
TENURE                              False
dtype: bool

In [106]:
A = dtst.iloc[:,1:-1]
B = dtst.iloc[:,-1]
print(A.shape,B.shape)

(8950, 16) (8950,)


1.a) Applying PCA on CC dataset.


In [107]:
pca = PCA(3)
a_pca = pca.fit_transform(A)
principalDf = pd.DataFrame(data = a_pca, columns = ['principal component 1', 'principal component 2', 'principal component 3'])
finalDf = pd.concat([principalDf, dtst.iloc[:,-1]], axis = 1)
finalDf.head()

principal component 1  principal component 2  principal component 3  TENURE
0           -4326.383979             921.566882             183.708383      12
1            4118.916665           -2432.846346            2369.969289      12
2            1497.907641           -1997.578694           -2125.631328      12
3            1394.548536           -1488.743453           -2431.799649      12
4           -3743.351896             757.342657             512.476492      12

In [108]:
#1.b Apply K Means on PCA Result
A = finalDf.iloc[:,0:-1]
B = finalDf.iloc[:,-1]

In [109]:
ncluster = 3
#this is k in kmeans
km = KMeans(n_clusters=ncluster)
km.fit(A)

B_cluster_kmeans = km.predict(A)
#predicting the cluster for each data point

print(classification_report(B,B_cluster_kmeans, zero_division=1))
print(confusion_matrix(B, B_cluster_kmeans))
#summary of the predictions made by the classifier

train_accuracy = accuracy_score(B, B_cluster_kmeans)
print("\nAccuracy for our Training dataset with PCA:", train_accuracy)

score = metrics.silhouette_score(A, B_cluster_kmeans)
print("Sihouette Score: ",score) 
#Calculated sihouette Score

              precision    recall  f1-score   support

           0       0.00      1.00      0.00       0.0
           1       0.00      1.00      0.00       0.0
           2       0.00      1.00      0.00       0.0
           6       1.00      0.00      0.00     204.0
           7       1.00      0.00      0.00     190.0
           8       1.00      0.00      0.00     196.0
           9       1.00      0.00      0.00     175.0
          10       1.00      0.00      0.00     236.0
          11       1.00      0.00      0.00     365.0
          12       1.00      0.00      0.00    7584.0

    accuracy                           0.00    8950.0
   macro avg       0.70      0.30      0.00    8950.0
weighted avg       1.00      0.00      0.00    8950.0

[[   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [  28  175    1    0    0    0    0    0    0    0]
 [  15  173    2    0    0   

Sihouette Score always ranges from −1 to +1
High value indicates that the object is well matched to its own cluster and poorly matched to neighboring clusters.

In [110]:
a = dtst.iloc[:,1:-1]
b = dtst.iloc[:,-1]
print(a.shape,b.shape)

(8950, 16) (8950,)


In [111]:
#Scaling
scaler = StandardScaler()
scaler.fit(a)
A_scaled_array = scaler.transform(a)
#PCA
pca = PCA(3)
B_pca = pca.fit_transform(A_scaled_array)
principalDf = pd.DataFrame(data = a_pca, columns = ['principal component 1', 'principal component 2','principal component 3'])
finalDf = pd.concat([principalDf, dtst.iloc[:,-1]], axis = 1)
finalDf.head()

principal component 1  principal component 2  principal component 3  TENURE
0           -4326.383979             921.566882             183.708383      12
1            4118.916665           -2432.846346            2369.969289      12
2            1497.907641           -1997.578694           -2125.631328      12
3            1394.548536           -1488.743453           -2431.799649      12
4           -3743.351896             757.342657             512.476492      12

In [112]:
A = finalDf.iloc[:,0:-1]
B = finalDf["TENURE"]
print(A.shape,B.shape)

(8950, 3) (8950,)


In [113]:
A_train, A_test, B_train, B_test = train_test_split(A,B, test_size=0.34,random_state=0)
nclusters = 3 
# this is the k in kmeans
km = KMeans(n_clusters=nclusters)
km.fit(A_train,B_train)


# predict the cluster for each training data point
B_clus_train = km.predict(A_train)

# Summary of the predictions made by the classifier
print(classification_report(B_train, B_clus_train, zero_division=1))
print(confusion_matrix(B_train, B_clus_train))

train_accuracy = accuracy_score(B_train, B_clus_train)
print("Accuracy of Training dataset with PCA:", train_accuracy)

#Calculate sihouette Score
score = metrics.silhouette_score(A_train, B_clus_train)
print("Sihouette Score: ",score) 

"""
Sihouette Score- ranges from −1 to +1 , a high value indicates that the object is well matched to its own cluster and poorly matched to neighboring clusters.
"""

              precision    recall  f1-score   support

           0       0.00      1.00      0.00       0.0
           1       0.00      1.00      0.00       0.0
           2       0.00      1.00      0.00       0.0
           6       1.00      0.00      0.00     139.0
           7       1.00      0.00      0.00     135.0
           8       1.00      0.00      0.00     128.0
           9       1.00      0.00      0.00     118.0
          10       1.00      0.00      0.00     151.0
          11       1.00      0.00      0.00     262.0
          12       1.00      0.00      0.00    4974.0

    accuracy                           0.00    5907.0
   macro avg       0.70      0.30      0.00    5907.0
weighted avg       1.00      0.00      0.00    5907.0

[[   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [  16  123    0    0    0    0    0    0    0    0]
 [   9  126    0    0    0   

'\nSihouette Score- ranges from −1 to +1 , a high value indicates that the object is well matched to its own cluster and poorly matched to neighboring clusters.\n'

In [114]:
#predicting the cluster for each testing data point
B_clus_test = km.predict(A_test)

# Summary of the predictions made by the classifier
print(classification_report(B_test, B_clus_test, zero_division=1))
print(confusion_matrix(B_test, B_clus_test))

train_accuracy = accuracy_score(B_test, B_clus_test)
print("\nAccuracy of Training dataset with PCA:", train_accuracy)

#Calculate sihouette Score
score = metrics.silhouette_score(A_test, B_clus_test)
print("Sihouette Score: ",score) 

"""
Sihouette Score- ranges from −1 to +1 , a high value indicates that the object is well matched to its own cluster and poorly matched to neighboring clusters.
"""

              precision    recall  f1-score   support

           0       0.00      1.00      0.00       0.0
           1       0.00      1.00      0.00       0.0
           2       0.00      1.00      0.00       0.0
           6       1.00      0.00      0.00      65.0
           7       1.00      0.00      0.00      55.0
           8       1.00      0.00      0.00      68.0
           9       1.00      0.00      0.00      57.0
          10       1.00      0.00      0.00      85.0
          11       1.00      0.00      0.00     103.0
          12       1.00      0.00      0.00    2610.0

    accuracy                           0.00    3043.0
   macro avg       0.70      0.30      0.00    3043.0
weighted avg       1.00      0.00      0.00    3043.0

[[   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [  12   53    0    0    0    0    0    0    0    0]
 [   7   47    1    0    0   

'\nSihouette Score- ranges from −1 to +1 , a high value indicates that the object is well matched to its own cluster and poorly matched to neighboring clusters.\n'

# 2nd question

Use pd_speech_features.csv

In [115]:
dtst = pd.read_csv('C:/Users/deeks/Downloads/datasets(2)/datasets/pd_speech_features.csv')


In [116]:
dtst

id  gender      PPE      DFA     RPDE  numPulses  numPeriodsPulses  \
0      0       1  0.85247  0.71826  0.57227        240               239   
1      0       1  0.76686  0.69481  0.53966        234               233   
2      0       1  0.85083  0.67604  0.58982        232               231   
3      1       0  0.41121  0.79672  0.59257        178               177   
4      1       0  0.32790  0.79782  0.53028        236               235   
..   ...     ...      ...      ...      ...        ...               ...   
751  250       0  0.80903  0.56355  0.28385        417               416   
752  250       0  0.16084  0.56499  0.59194        415               413   
753  251       0  0.88389  0.72335  0.46815        381               380   
754  251       0  0.83782  0.74890  0.49823        340               339   
755  251       0  0.81304  0.76471  0.46374        340               339   

     meanPeriodPulses  stdDevPeriodPulses  locPctJitter  ...  \
0            0.008064            0.000087       0.00218  ...   
1            0.008258            0.000073       0.00195  ...   
2            0.008340            0.000060       0.00176  ...   
3            0.010858            0.000183       0.00419  ...   
4            0.008162            0.002669       0.00535  ...   
..                ...                 ...           ...  ...   
751          0.004627            0.000052       0.00064  ...   
752          0.004550            0.000220       0.00143  ...   
753          0.005069            0.000103       0.00076  ...   
754          0.005679            0.000055       0.00092  ...   
755          0.005676            0.000037       0.00078  ...   

     tqwt_kurtosisValue_dec_28  tqwt_kurtosisValue_dec_29  \
0                       1.5620                     2.6445   
1                       1.5589                     3.6107   
2                       1.5643                     2.3308   
3                       3.7805                     3.5664   
4                       6.1727                     5.8416   
..                         ...                        ...   
751                     3.0706                     3.0190   
752                     1.9704                     1.7451   
753                    51.5607                    44.4641   
754                    19.1607                    12.8312   
755                    62.9927                    21.8152   

     tqwt_kurtosisValue_dec_30  tqwt_kurtosisValue_dec_31  \
0                       3.8686                     4.2105   
1                      23.5155                    14.1962   
2                       9.4959                    10.7458   
3                       5.2558                    14.0403   
4                       6.0805                     5.7621   
..                         ...                        ...   
751                     3.1212                     2.4921   
752                     1.8277                     2.4976   
753                    26.1586                     6.3076   
754                     8.9434                     2.2044   
755                     9.2457                     4.8555   

     tqwt_kurtosisValue_dec_32  tqwt_kurtosisValue_dec_33  \
0                       5.1221                     4.4625   
1                      11.0261                     9.5082   
2                      11.0177                     4.8066   
3                       4.2235                     4.6857   
4                       7.7817                    11.6891   
..                         ...                        ...   
751                     3.5844                     3.5400   
752                     5.2981                     4.2616   
753                     2.8601                     2.5361   
754                     1.9496                     1.9664   
755                     3.0551                     3.0415   

     tqwt_kurtosisValue_dec_34  tqwt_kurtosisValue_dec_35  \
0                       2.6202                     3.0004   
1  

In [117]:
dtst.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 756 entries, 0 to 755
Columns: 755 entries, id to class
dtypes: float64(749), int64(6)
memory usage: 4.4 MB


In [118]:
dtst.isnull().any()

id                           False
gender                       False
PPE                          False
DFA                          False
RPDE                         False
                             ...  
tqwt_kurtosisValue_dec_33    False
tqwt_kurtosisValue_dec_34    False
tqwt_kurtosisValue_dec_35    False
tqwt_kurtosisValue_dec_36    False
class                        False
Length: 755, dtype: bool

In [119]:
A = dtst.drop('class',axis=1).values
B = dtst['class'].values

2.a) Perform Scaling

In [120]:
#Scaling Data
scaler = StandardScaler()
A_Scale = scaler.fit_transform(A)

2.b) Applying PCA (k=3)

In [121]:
# Apply PCA with k =3
pca3 = PCA(n_components=3)
principalComponents = pca3.fit_transform(A_Scale)

principalDf = pd.DataFrame(data = principalComponents, columns = ['principal component 1', 'principal component 2','Principal Component 3'])

finalDf = pd.concat([principalDf, dtst[['class']]], axis = 1)
finalDf.head()

principal component 1  principal component 2  Principal Component 3  class
0             -10.047372               1.471073              -6.846403      1
1             -10.637725               1.583746              -6.830977      1
2             -13.516185              -1.253546              -6.818697      1
3              -9.155084               8.833591              15.290903      1
4              -6.764470               4.611462              15.637121      1

2.c) Using SVM to report performance

In [122]:
A = finalDf.drop('class',axis=1).values
B = finalDf['class'].values
A_train, A_test, B_train, B_test = train_test_split(A,B, test_size=0.34,random_state=0)

In [123]:
from sklearn.svm import SVC

svmClassifier = SVC()
svmClassifier.fit(A_train, B_train)

B_pred = svmClassifier.predict(A_test)

# Summary of the predictions made by the classifier
print(classification_report(B_test, B_pred, zero_division=1))
print(confusion_matrix(B_test, B_pred))
# Accuracy score
glass_acc_svc = accuracy_score(B_pred,B_test)
print('accuracy is',glass_acc_svc )

#Calculate sihouette Score
score = metrics.silhouette_score(A_test, B_pred)
print("Sihouette Score: ",score) 

              precision    recall  f1-score   support

           0       0.67      0.42      0.51        62
           1       0.84      0.93      0.88       196

    accuracy                           0.81       258
   macro avg       0.75      0.68      0.70       258
weighted avg       0.80      0.81      0.79       258

[[ 26  36]
 [ 13 183]]
accuracy is 0.810077519379845
Sihouette Score:  0.2504463574721257


# 3rd question

Applying Linear Discriminant Analysis (LDA) on Iris.csv dataset to reduce dimensionality of data to k=2. 

In [124]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
dtst = pd.read_csv('C:/Users/deeks/Downloads/datasets(2)/datasets/Iris.csv')
dtst.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [125]:
dtst.isnull().any()

Id               False
SepalLengthCm    False
SepalWidthCm     False
PetalLengthCm    False
PetalWidthCm     False
Species          False
dtype: bool

In [127]:
A = dtst.iloc[:,1:-1]
B = dtst.iloc[:,-1]
print(A.shape,B.shape)

(150, 4) (150,)


In [128]:
A_train, A_test, B_train, B_test = train_test_split(A,B, test_size=0.3, random_state=0)

In [129]:
sc = StandardScaler()
A_train = sc.fit_transform(A_train)
A_test = sc.transform(A_test)
le = LabelEncoder()
y = le.fit_transform(B)

In [130]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda = LDA(n_components=2)
A_train = lda.fit_transform(A_train, B_train)
A_test = lda.transform(A_test)
print(A_train.shape,A_test.shape)

(105, 2) (45, 2)


# 4th question

In [133]:
#Difference between PCA and LDA
"""Both LDA and PCA rely mainly on linear transformations and it's main aim to maximize the variance in lower dimension. PCA is however a unsupervised learning algorithm where LDA is a supervised learning algorithm. It means that PCA finds directions of maximum variance regardless of class labels while LDA finds directions of maximum class separability"""

'Both LDA and PCA rely on linear transformations and aim to maximize the variance in a lower dimension. PCA is an unsupervised learning algorithm while LDA is a supervised learning algorithm. This means that PCA finds directions of maximum variance regardless of class labels while LDA finds directions of maximum class separability'

In [134]:
#PCA
"""It reduces features into smaller subset of orthogonal variables, called principal components – linear combinations of the original variables. The first component captures the largest variability of the data, while the second captures the second largest, and so on."""

'It reduces the features into a smaller subset of orthogonal variables, called principal components – linear combinations of the original variables. The first component captures the largest variability of the data, while the second captures the second largest, and so on.'

In [135]:
#LDA
"""LDA finds the linear discriminants in order to maximize the variance between the different categories while minimizing the variance within the class."""

'LDA finds the linear discriminants in order to maximize the variance between the different categories while minimizing the variance within the class.'